name: Java CI 02 for deploy artifacts
run-name: ${{ github.actor }} will deploy artifacts ðŸš€
on: [pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Set up JDK 19
        uses: actions/setup-java@v3
        with:
          java-version: 19
          distribution: adopt
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots package
      - name: Move artifacts
        run: mkdir staging && cp target/*.jar staging
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Package
          path: staging
      - name: Deploy to staging server
        uses: actions/setup-node@v2
        with:
          node-version: 14
          script: |
            npm install -g now
            now --token $NOW_TOKEN --prod
      - name: CINotify Email
        uses: cinotify/github-action@main
        with:
          to: 'adam.khalil@fh-joanneum.at'
          subject: 'building '
          body: 'This is a notification from GitHub actions.'
